; SP0256-AL2 Allophone List
; Taken from http://www.cpcwiki.eu/index.php/SP0256_Allophones
; Name Value Short Example Funny Actual

SPEAK_PA1:	equ  00h	; PA1   PAUSE     10ms    6.4ms
SPEAK_PA2:	equ  01h	; PA2   PAUSE     30ms   25.6ms
SPEAK_PA3:	equ  02h	; PA3   PAUSE     50ms   44.8ms
SPEAK_PA4:	equ  03h	; PA4   PAUSE    100ms   96.0ms
SPEAK_PA5:	equ  04h	; PA5   PAUSE    200ms  198.4ms

SPEAK_OY:	equ  05h	; /OY/  Boy      420ms  291.2ms
SPEAK_AY:	equ  06h	; /AY/  Sky      260ms  172.9ms
SPEAK_EH:	equ  07h	; /EH/  End       70ms   54.6ms
SPEAK_KK3:	equ  08h	; /KK3/ Comb     120ms   76.8ms
SPEAK_PP:	equ  09h	; /PP/  Pow      210ms  147.2ms
SPEAK_JH:	equ  0Ah	; /JH/  Dodge    140ms   98.4ms
SPEAK_NN1:	equ  0Bh	; /NN1/ Thin     140ms  172.9ms
SPEAK_IH:	equ  0Ch	; /IH/  Sit       70ms   45.5ms
SPEAK_TT2:	equ  0Dh	; /TT2/ To       140ms   96.0ms
SPEAK_RR1:	equ  0Eh	; /RR1/ Rural    170ms  127.4ms
SPEAK_AX:	equ  0Fh	; /AX/  Succeed   70ms   54.6ms
SPEAK_MM:	equ  10h	; /MM/  Milk     180ms  182.0ms
SPEAK_TT1:	equ  11h	; /TT1/ Part     100ms   76.8ms
SPEAK_DH1:	equ  12h	; /DH1/ They     290ms  136.5ms
SPEAK_IY:	equ  13h	; /IY/  See      250ms  172.9ms
SPEAK_EY:	equ  14h	; /EY/  Beige    280ms  200.2ms
SPEAK_DD1:	equ  15h	; /DD1/ Could     70ms   45.5ms
SPEAK_UW1:	equ  16h	; /UW1/ To       100ms   63.7ms
SPEAK_AO:	equ  17h	; /AO/  Aught    100ms   72.8ms
SPEAK_AA:	equ  18h	; /AA/  Hot      100ms   63.7ms
SPEAK_YY2:	equ  19h	; /YY2/ Yes      180ms  127.4ms
SPEAK_AE:	equ  1Ah	; /AE/  Hat      120ms   81.9ms
SPEAK_HH1:	equ  1Bh	; /HH1/ He       130ms   89.6ms
SPEAK_BB1:	equ  1Ch	; /BB1/ Business  80ms   36.4ms
SPEAK_TH:	equ  1Dh	; /TH/  Thin     180ms  128.0ms
SPEAK_UH:	equ  1Eh	; /UH/  Book     100ms   72.8ms
SPEAK_UW2:	equ  1Fh	; /UW2/ Food     260ms  172.9ms

SPEAK_AW:	equ	 20h 	; /AW/  Out      370ms  254.8ms
SPEAK_DD2:	equ  21h 	; /DD2/ Do       160ms   72.1ms
SPEAK_GG3:	equ  22h 	; /GG3/ Wig      140ms  110.5ms
SPEAK_VV:	equ  23h 	; /VV/  Vest     190ms  127.4ms
SPEAK_GG1:	equ  24h 	; /GG1/ Got       80ms   72.1ms
SPEAK_SH:	equ  25h 	; /SH/  Ship     160ms  198.4ms
SPEAK_ZH:	equ  26h 	; /ZH/  Azure    190ms  134.1ms
SPEAK_RR2:	equ  27h 	; /RR2/ Brain    120ms   81.9ms
SPEAK_FF:	equ  28h 	; /FF/  Food     150ms  108.8ms
SPEAK_KK2:	equ  29h 	; /KK2/ Sky      190ms  134.4ms
SPEAK_KK1:	equ  2Ah 	; /KK1/ Can't    160ms  115.2ms
SPEAK_ZZ:	equ  2Bh 	; /ZZ/  Zoo      210ms  148.6ms
SPEAK_NG:	equ  2Ch 	; /NG/  Anchor   220ms  200.2ms
SPEAK_LL:	equ  2Dh 	; /LL/  Lake     110ms   81.9ms
SPEAK_WW:	equ  2Eh 	; /WW/  Wool     180ms  145.6ms
SPEAK_XR:	equ  2Fh 	; /XR/  Repair   360ms  245.7ms
SPEAK_WH:	equ  30h 	; /WH/  Whig     200ms  145.2ms
SPEAK_YY1:	equ  31h 	; /YY1/ Yes      130ms   91.0ms
SPEAK_CH:	equ  32h 	; /CH/  Church   190ms  147.2ms
SPEAK_ER1:	equ  33h 	; /ER1/ Letter   160ms  109.2ms
SPEAK_ER2:	equ  34h 	; /ER2/ Fir      300ms  209.3ms
SPEAK_OW:	equ  35h 	; /OW/  Beau     240ms  172.9ms
SPEAK_DH2:	equ  36h 	; /DH2/ Bath     240ms  182.0ms
SPEAK_SS:	equ  37h 	; /SS/  Vest      90ms   64.0ms
SPEAK_NN2:	equ  38h 	; /NN2/ No       190ms  136.5ms
SPEAK_HH2:	equ  39h 	; /HH2/ Hoe      180ms  126.0ms
SPEAK_OR:	equ  3Ah 	; /OR/  Store    330ms  236.6ms
SPEAK_AR:	equ  3Bh 	; /AR/  Alarm    290ms  200.2ms
SPEAK_YR:	equ  3Ch 	; /YR/  Clear    350ms  245.7ms
SPEAK_GG2:	equ  3Dh 	; /GG2/ Guest     40ms   69.4ms
SPEAK_EL:	equ  3Eh 	; /EL/  Saddle   190ms  136.5ms
SPEAK_BB2:	equ  3Fh 	; /BB2/ Business  50ms   50.2ms

